// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

// Ediscovery is navigation property
func (b *ComplianceRequestBuilder) Ediscovery() *EdiscoveryEdiscoveryrootRequestBuilder {
	bb := &EdiscoveryEdiscoveryrootRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/ediscovery"
	return bb
}
