// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

import "context"

// EdiscoveryEdiscoveryrootRequestBuilder is request builder for EdiscoveryEdiscoveryroot
type EdiscoveryEdiscoveryrootRequestBuilder struct{ BaseRequestBuilder }

// Request returns EdiscoveryEdiscoveryrootRequest
func (b *EdiscoveryEdiscoveryrootRequestBuilder) Request() *EdiscoveryEdiscoveryrootRequest {
	return &EdiscoveryEdiscoveryrootRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// EdiscoveryEdiscoveryrootRequest is request for EdiscoveryEdiscoveryroot
type EdiscoveryEdiscoveryrootRequest struct{ BaseRequest }

// Get performs GET request for EdiscoveryEdiscoveryroot
func (r *EdiscoveryEdiscoveryrootRequest) Get(ctx context.Context) (resObj *EdiscoveryEdiscoveryroot, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for EdiscoveryEdiscoveryroot
func (r *EdiscoveryEdiscoveryrootRequest) Update(ctx context.Context, reqObj *EdiscoveryEdiscoveryroot) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for EdiscoveryEdiscoveryroot
func (r *EdiscoveryEdiscoveryrootRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}
