// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

import "context"

// TermStoreStoreRequestBuilder is request builder for TermStoreStore
type TermStoreStoreRequestBuilder struct{ BaseRequestBuilder }

// Request returns TermStoreStoreRequest
func (b *TermStoreStoreRequestBuilder) Request() *TermStoreStoreRequest {
	return &TermStoreStoreRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// TermStoreStoreRequest is request for TermStoreStore
type TermStoreStoreRequest struct{ BaseRequest }

// Get performs GET request for TermStoreStore
func (r *TermStoreStoreRequest) Get(ctx context.Context) (resObj *TermStoreStore, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for TermStoreStore
func (r *TermStoreStoreRequest) Update(ctx context.Context, reqObj *TermStoreStore) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for TermStoreStore
func (r *TermStoreStoreRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}
